wandb_version: 1

exp_name:
  desc: null
  value: Energyplus_Env
seed:
  desc: null
  value: 1
cuda:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: TEST
wandb_entity:
  desc: null
  value: shandong111
_wandb:
  desc: null
  value:
    code_path: code/main.py
    python_version: 3.11.9
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1744726529
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      - 61
      4: 3.11.9
      5: 0.17.7
      8:
      - 3
      - 5
      13: windows-amd64
